// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://smcwvrywntxayuzsijkg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNtY3d2cnl3bnR4YXl1enNpamtnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQ0NzcxMTQsImV4cCI6MjA2MDA1MzExNH0.0kZaV3FrCU0_I9Kl6W3SrF5NoVLz0Y8QLR-XDoVQqzQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);